FC 2025 PLAYERS - DATA SCIENCE PROJECT

In [25]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

Load Data

In [26]:
data = pd.read_csv('./archive/all_players.csv')

In [27]:
data

,Unnamed: 0.1,Unnamed: 0,Rank,Name,OVR,PAC,SHO,PAS,DRI,DEF,...,Nation,League,Team,play style,url,GK Diving,GK Handling,GK Kicking,GK Positioning,GK Reflexes
0,0,0,1,Kylian Mbappé,91,97,90,80,92,36,...,France,LALIGA EA SPORTS,Real Madrid,"Quick Step+, Acrobatic, Finesse Shot, Flair, R...",https://www.ea.com/games/ea-sports-fc/ratings/...,NaN,NaN,NaN,NaN,NaN
1,1,1,2,Rodri,91,66,80,86,84,87,...,Spain,Premier League,Manchester City,"Tiki Taka+, Aerial, Bruiser, Long Ball Pass, P...",https://www.ea.com/games/ea-sports-fc/ratings/...,NaN,NaN,NaN,NaN,NaN
2,2,2,4,Erling Haaland,91,88,92,70,81,45,...,Norway,Premier League,Manchester City,"Acrobatic+, Bruiser, Power Header, Power Shot,...",https://www.ea.com/games/ea-sports-fc/ratings/...,NaN,NaN,NaN,NaN,NaN
3,3,3,5,Jude Bellingham,90,80,87,83,88,78,...,England,LALIGA EA SPORTS,Real Madrid,"Relentless+, Flair, Intercept, Slide Tackle, T...",https://www.ea.com/games/ea-sports-fc/ratings/...,NaN,NaN,NaN,NaN,NaN
4,4,4,7,Vini Jr.,90,95,84,81,91,29,...,Brazil,LALIGA EA SPORTS,Real Madrid,"Quick Step+, Chip Shot, Finesse Shot, First To...",https://www.ea.com/games/ea-sports-fc/ratings/...,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17732,17732,1571,17146,Araya Dennis,53,42,57,49,52,25,...,England,Barclays WSL,Spurs,NaN,https://www.ea.com/games/ea-sports-fc/ratings/...,NaN,NaN,NaN,NaN,NaN
17733,17733,1572,17146,Alexia Férnandez,53,53,55,51,53,34,...,Spain,Liga F,Granada CF,NaN,https://www.ea.com/games/ea-sports-fc/ratings/...,NaN,NaN,NaN,NaN,NaN
17734,17734,1573,17146,Aleigh Gambone,53,60,58,53,56,49,...,United States,Scottish Women's League,Glasgow City FC,NaN,https://www.ea.com/games/ea-sports-fc/ratings/...,NaN,NaN,NaN,NaN,NaN
17735,17735,1574,17146,Joy Lysser,53,61,52,48,56,53,...,Switzerland,Schweizer Damen Liga,FC Zürich,NaN,https://www.ea.com/games/ea-sports-fc/ratings/...,NaN,NaN,NaN,NaN,NaN
17736,17736,1575,17146,Kateřina Vithová,53,60,49,53,54,27,...,Czech Republic,Ceska Liga Žen,Slavia Praha,NaN,https://www.ea.com/games/ea-sports-fc/ratings/...,NaN,NaN,NaN,NaN,NaN

In [28]:
data.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'Rank', 'Name', 'OVR', 'PAC', 'SHO',
       'PAS', 'DRI', 'DEF', 'PHY', 'Acceleration', 'Sprint Speed',
       'Positioning', 'Finishing', 'Shot Power', 'Long Shots', 'Volleys',
       'Penalties', 'Vision', 'Crossing', 'Free Kick Accuracy',
       'Short Passing', 'Long Passing', 'Curve', 'Dribbling', 'Agility',
       'Balance', 'Reactions', 'Ball Control', 'Composure', 'Interceptions',
       'Heading Accuracy', 'Def Awareness', 'Standing Tackle',
       'Sliding Tackle', 'Jumping', 'Stamina', 'Strength', 'Aggression',
       'Position', 'Weak foot', 'Skill moves', 'Preferred foot', 'Height',
       'Weight', 'Alternative positions', 'Age', 'Nation', 'League', 'Team',
       'play style', 'url', 'GK Diving', 'GK Handling', 'GK Kicking',
       'GK Positioning', 'GK Reflexes'],
      dtype='object')

* PAC - Pace (running speed)
* SHO - Shooting (ability to shoot the ball)
* PAS - Passing (ability to pass the ball)
* DRI - Dribbling (ability to control the ball while running)
* DEF - Defending (ability to defend against the opponent)
* PHY - Physicality (strength, stamina, aggression, etc.)

### TOP 100 PLAYER BY COUNTRY CHART

In [29]:
TopCountry = data.head(100)

In [30]:
TopCountry

,Unnamed: 0.1,Unnamed: 0,Rank,Name,OVR,PAC,SHO,PAS,DRI,DEF,...,Nation,League,Team,play style,url,GK Diving,GK Handling,GK Kicking,GK Positioning,GK Reflexes
0,0,0,1,Kylian Mbappé,91,97,90,80,92,36,...,France,LALIGA EA SPORTS,Real Madrid,"Quick Step+, Acrobatic, Finesse Shot, Flair, R...",https://www.ea.com/games/ea-sports-fc/ratings/...,NaN,NaN,NaN,NaN,NaN
1,1,1,2,Rodri,91,66,80,86,84,87,...,Spain,Premier League,Manchester City,"Tiki Taka+, Aerial, Bruiser, Long Ball Pass, P...",https://www.ea.com/games/ea-sports-fc/ratings/...,NaN,NaN,NaN,NaN,NaN
2,2,2,4,Erling Haaland,91,88,92,70,81,45,...,Norway,Premier League,Manchester City,"Acrobatic+, Bruiser, Power Header, Power Shot,...",https://www.ea.com/games/ea-sports-fc/ratings/...,NaN,NaN,NaN,NaN,NaN
3,3,3,5,Jude Bellingham,90,80,87,83,88,78,...,England,LALIGA EA SPORTS,Real Madrid,"Relentless+, Flair, Intercept, Slide Tackle, T...",https://www.ea.com/games/ea-sports-fc/ratings/...,NaN,NaN,NaN,NaN,NaN
4,4,4,7,Vini Jr.,90,95,84,81,91,29,...,Brazil,LALIGA EA SPORTS,Real Madrid,"Quick Step+, Chip Shot, Finesse Shot, First To...",https://www.ea.com/games/ea-sports-fc/ratings/...,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,95,149,Julián Álvarez,84,85,84,80,85,57,...,Argentina,LALIGA EA SPORTS,Atlético de Madrid,"Press Proven+, Finesse Shot, Flair",https://www.ea.com/games/ea-sports-fc/ratings/...,NaN,NaN,NaN,NaN,NaN
96,96,96,149,Iago Aspas,84,81,86,79,86,35,...,Spain,LALIGA EA SPORTS,RC Celta,"Chip Shot+, Dead Ball, Finesse Shot, Incisive ...",https://www.ea.com/games/ea-sports-fc/ratings/...,NaN,NaN,NaN,NaN,NaN
97,97,97,149,Yassine Bounou,84,81,82,77,86,38,...,Morocco,ROSHN Saudi League,Al Hilal,"Far Throw+, Cross Claimer, Footwork",https://www.ea.com/games/ea-sports-fc/ratings/...,81.0,82.0,77.0,83.0,86.0
98,98,98,149,Federico Chiesa,84,93,83,76,86,52,...,Italy,Premier League,Liverpool,"Finesse Shot, Flair, Quick Step, Rapid, Trivela",https://www.ea.com/games/ea-sports-fc/ratings/...,NaN,NaN,NaN,NaN,NaN
99,99,99,149,Kingsley Coman,84,89,75,79,87,30,...,France,Bundesliga,FC Bayern München,"Rapid+, Acrobatic, First Touch, Flair, Quick Step",https://www.ea.com/games/ea-sports-fc/ratings/...,NaN,NaN,NaN,NaN,NaN

In [31]:
from collections import Counter

In [32]:
TopCountryCountdict = Counter(TopCountry['Nation'])

In [33]:
TopCountryCountdict

Counter({'France': 11,
         'Germany': 11,
         'England': 10,
         'Brazil': 10,
         'Portugal': 9,
         'Spain': 8,
         'Italy': 6,
         'Argentina': 6,
         'Switzerland': 4,
         'Belgium': 3,
         'Holland': 3,
         'Norway': 2,
         'Uruguay': 2,
         'Georgia': 2,
         'Egypt': 1,
         'Poland': 1,
         'Slovenia': 1,
         'Nigeria': 1,
         'Korea Republic': 1,
         'Croatia': 1,
         'Turkey': 1,
         'Austria': 1,
         'Sweden': 1,
         'Algeria': 1,
         'Serbia': 1,
         'Scotland': 1,
         'Morocco': 1})

In [34]:
type(TopCountryCountdict)

collections.Counter

In [35]:
TopCountryCount = pd.DataFrame.from_dict(TopCountryCountdict, orient='index').reset_index()

In [36]:
TopCountryCount

             index   0
0           France  11
1            Spain   8
2           Norway   2
3          England  10
4           Brazil  10
5          Belgium   3
6            Italy   6
7        Argentina   6
8          Holland   3
9          Germany  11
10           Egypt   1
11        Portugal   9
12          Poland   1
13         Uruguay   2
14        Slovenia   1
15     Switzerland   4
16         Nigeria   1
17  Korea Republic   1
18         Croatia   1
19          Turkey   1
20         Austria   1
21          Sweden   1
22         Georgia   2
23         Algeria   1
24          Serbia   1
25        Scotland   1
26         Morocco   1

In [37]:
TopCountryCount = TopCountryCount.rename(columns={0:'PlayerCount'})

In [38]:
TopCountryCount.dtypes

index          object
PlayerCount     int64
dtype: object

In [39]:
TopCountryCount['value'] = TopCountryCount.PlayerCount / TopCountryCount['PlayerCount'].sum()

In [40]:
TopCountryCount

             index  PlayerCount  value
0           France           11   0.11
1            Spain            8   0.08
2           Norway            2   0.02
3          England           10   0.10
4           Brazil           10   0.10
5          Belgium            3   0.03
6            Italy            6   0.06
7        Argentina            6   0.06
8          Holland            3   0.03
9          Germany           11   0.11
10           Egypt            1   0.01
11        Portugal            9   0.09
12          Poland            1   0.01
13         Uruguay            2   0.02
14        Slovenia            1   0.01
15     Switzerland            4   0.04
16         Nigeria            1   0.01
17  Korea Republic            1   0.01
18         Croatia            1   0.01
19          Turkey            1   0.01
20         Austria            1   0.01
21          Sweden            1   0.01
22         Georgia            2   0.02
23         Algeria            1   0.01
24          Serbia            1   0.01
25        Scotland            1   0.01
26         Morocco            1   0.01

In [41]:
toptop =TopCountryCount.sort_values(by=['value'], ascending= False)

In [42]:
top10countriesCount = toptop.head(10)

In [43]:
top10countriesCount

          index  PlayerCount  value
0        France           11   0.11
9       Germany           11   0.11
3       England           10   0.10
4        Brazil           10   0.10
11     Portugal            9   0.09
1         Spain            8   0.08
7     Argentina            6   0.06
6         Italy            6   0.06
15  Switzerland            4   0.04
8       Holland            3   0.03

### Group player by postion and choose the best

In [50]:
AllPostions = data['Position'].drop_duplicates()

In [51]:
AllPostions

0      ST
1     CDM
3     CAM
4      LW
5      CM
8      GK
12     CB
14     RW
32     LB
51     LM
54     RB
76     RM
Name: Position, dtype: object

* GK - Goalkeeper
* RB/LB - Fullback
* CB - Center Back
* CDM - Central Defensive Midfielder
* CM - Central Midfielder
* RM/LM - Right/Left Midfielder
* CAM - Attacking Midfielder
* RW/LW - Right/Left Wing
* ST - Striker

In [56]:
data['Sprint Speed']

0        97
1        66
2        94
3        80
4        95
         ..
17732    41
17733    53
17734    62
17735    62
17736    60
Name: Sprint Speed, Length: 17737, dtype: int64

Luźne przemyślenia żebym nie zapomniał - kilka różnych modeli ML dla każdej z pozycji, sprawdzić jak maszyna wybierze zawadoników

In [64]:
St_players = data.loc[data['Position'] == 'ST']
Gk_players = data.loc[data['Position'] == 'GK']
Rb_players = data.loc[data['Position'] == 'RB']
Lb_players = data.loc[data['Position'] == 'LB']
Cb_players = data.loc[data['Position'] == 'CB']
Cdm_players = data.loc[data['Position'] == 'CDM']
Cm_players = data.loc[data['Position'] == 'CM']
Rm_players = data.loc[data['Position'] == 'RM']
Lm_players = data.loc[data['Position'] == 'LM']
Cam_players = data.loc[data['Position'] == 'CAM']
Rw_players = data.loc[data['Position'] == 'RW']
Lw_players = data.loc[data['Position'] == 'LW']

In [ ]:
St_players['Position'].drop_duplicates() #check for sure that we dont have other postions

0    ST
Name: Position, dtype: object

In [68]:
from sklearn.model_selection import train_test_split

In [69]:
train_set = St_players.sample(frac=0.8, random_state=42)

In [71]:
train_set

,Unnamed: 0.1,Unnamed: 0,Rank,Name,OVR,PAC,SHO,PAS,DRI,DEF,...,Nation,League,Team,play style,url,GK Diving,GK Handling,GK Kicking,GK Positioning,GK Reflexes
11104,11104,11104,12239,Brandon Hanlan,63,84,60,52,64,35,...,England,EFL League One,Wycombe,NaN,https://www.ea.com/games/ea-sports-fc/ratings/...,NaN,NaN,NaN,NaN,NaN
2876,2876,2876,3521,David Datro Fofana,72,83,70,60,75,25,...,Côte d'Ivoire,Premier League,Chelsea,"Flair, Technical",https://www.ea.com/games/ea-sports-fc/ratings/...,NaN,NaN,NaN,NaN,NaN
10517,10517,10517,11203,Marko Raguž,64,58,63,59,68,22,...,Austria,Ö. Bundesliga,FK Austria Wien,NaN,https://www.ea.com/games/ea-sports-fc/ratings/...,NaN,NaN,NaN,NaN,NaN
3090,3090,3090,3521,Victor Olatunji,72,77,67,55,66,24,...,Nigeria,Česká Liga,Sparta Praha,Aerial,https://www.ea.com/games/ea-sports-fc/ratings/...,NaN,NaN,NaN,NaN,NaN
3633,3633,3633,4260,Grejohn Kyei,71,62,70,54,70,27,...,France,1A Pro League,Standard Liège,NaN,https://www.ea.com/games/ea-sports-fc/ratings/...,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6473,6473,6473,6884,Seo Jin Su,68,82,68,58,71,22,...,Korea Republic,K League 1,Jeju United,Technical,https://www.ea.com/games/ea-sports-fc/ratings/...,NaN,NaN,NaN,NaN,NaN
6436,6436,6436,6884,Armando Sadiku,68,65,69,50,63,38,...,Albania,ISL,FC Goa,NaN,https://www.ea.com/games/ea-sports-fc/ratings/...,NaN,NaN,NaN,NaN,NaN
1575,1575,1575,1888,Ezequiel Ponce,75,75,75,61,73,38,...,Argentina,MLS,Houston Dynamo,Flair,https://www.ea.com/games/ea-sports-fc/ratings/...,NaN,NaN,NaN,NaN,NaN
2035,2035,2035,2318,Raúl Ruidíaz,74,71,77,65,76,32,...,Peru,MLS,Sounders FC,"Flair, Technical, Trivela",https://www.ea.com/games/ea-sports-fc/ratings/...,NaN,NaN,NaN,NaN,NaN
11607,11607,11607,12239,Wang Ziming,63,81,61,50,61,32,...,China PR,CSL,Beijing FC,Rapid,https://www.ea.com/games/ea-sports-fc/ratings/...,NaN,NaN,NaN,NaN,NaN